### ISSUE TITLE
Units for Total absorption cross section

### ISSUE THREAD

**Issue by SergeyRa** [oasys-kit/SR-xraylib#4]
The Total absorption cross section calculation provides result in g/cm3, but shouldn't it be in cm2?

![Screenshot from 2020-02-25 13-05-22](https://user-images.githubusercontent.com/42113408/75219709-1f68d700-57d0-11ea-9212-4222fc0c832a.png)

**Comment by srio** [comment]
Yes, you are right. Thanks to notify it. I fixed it, it will be available in the next xoppy release.
